#include <openenclave/host.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "oe_crypto_app_u.h"  // Generated by oeedger8r

#define ENCLAVE_PATH "enclave/enclave.signed"  // Adjust path as needed
#define DATA "Bare-SGX rocks!"
#define TAG_LEN 32

int main(int argc, const char* argv[])
{
    oe_enclave_t* enclave = NULL;
    oe_result_t result;
    uint8_t digest[TAG_LEN] = {0};

    // Load enclave
    result = oe_create_oe_crypto_app_enclave(
        ENCLAVE_PATH,
        OE_ENCLAVE_TYPE_SGX,
        OE_ENCLAVE_FLAG_DEBUG,
        NULL,
        0,
        &enclave);

    if (result != OE_OK)
    {
        fprintf(stderr, "Failed to create enclave: %s\n", oe_result_str(result));
        return 1;
    }

    // Prepare data
    uint8_t* data = (uint8_t*)DATA;
    uint32_t data_len = (uint32_t)strlen(DATA);

    // Call enclave function
    int retval;
    result = oe_encl_op_hmac(enclave, &retval, digest, data, data_len);
    if (result != OE_OK || retval != 1)
    {
        fprintf(stderr, "Failed to call oe_encl_op_hmac: %s\n", oe_result_str(result));
        oe_terminate_enclave(enclave);
        return 1;
    }

    // Print HMAC result
    printf("Hashing \"Bare-SGX Rocks\" using Open Enclave (HMAC-SHA256):\n");
    for (int i = 0; i < TAG_LEN; ++i)
        printf("%02x", digest[i]);
    printf("\n");

    // Cleanup
    oe_terminate_enclave(enclave);
    return 0;
}