name: CI for C Programs
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '00 08 * * MON'

jobs:
  build:
    name: Build and Test Compilation
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Fetch submodules
        run: |
          git submodule init
          git submodule update
        
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -yqq install build-essential libelf-dev

      - name: Build and load /dev/sgx-step
        run: |
          cd $GITHUB_WORKSPACE/external/sgx-step/kernel/
          #./install_SGX_driver.sh
          make clean load

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Fetch submodules
        run: |
          git submodule init
          git submodule update

      - name: Patch and install Intel SGX SDK
        run: |
          cd $GITHUB_WORKSPACE/external/sgx-step/sdk/intel-sdk/
          sudo apt-get update
          bash -x ./install_SGX_SDK.sh
          source /opt/intel/sgxsdk/environment
          sudo service aesmd status

      - name: Run Intel SGX SDK sample code in simulator
        run: |
          source /opt/intel/sgxsdk/environment
          cd $GITHUB_WORKSPACE/external/sgx-step/sdk/intel-sdk/linux-sgx/SampleCode/LocalAttestation
          make SGX_MODE=SIM
          cd bin
          ldd ./app
          ./app
          
      - name: Build C programs
        run: |
          source /opt/intel/sgxsdk/environment
          for dir in app/ecall_asm app/crypto-app app/speed-test-sdk app/bare-step app/ecall_ptr app/bare-crypto-app; do
            echo "Building in $dir"
            cd $dir
            make
            if [ -f "app" ]; then
              echo "Binary 'app' created in $dir"
            else
              echo "Error: Binary 'app' not found in $dir"
              exit 1
            fi
            cd -
          done
