name: CI for C Programs

# Trigger the workflow on push or pull requests to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test Compilation
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install build tools and SGX dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential gcc make libssl-dev
        # Install Intel SGX SDK (example for Ubuntu)
        wget https://download.01.org/intel-sgx/sgx-linux/2.17.1/distro/ubuntu20.04-server/sgx_linux_x64_sdk_2.17.101.1.bin
        chmod +x sgx_linux_x64_sdk_2.17.101.1.bin
        ./sgx_linux_x64_sdk_2.17.101.1.bin --prefix=/opt/intel
        echo "source /opt/intel/sgxsdk/environment" >> $SGX_SDK

      # Step 3: Build the project
      - name: Build C programs
        working-directory: ./app/speed-test-bare
        run: |
          make clean
          make

      # Step 4: Verify output
      - name: Check for output binary
        working-directory: ./app/speed-test-bare
        run: |
          if [ -f "app" ]; then
            echo "Binary 'app' successfully created"
          else
            echo "Error: Binary 'app' not found"
            exit 1
          fi
